# Generated by Django 3.2.3 on 2021-05-25 07:36

from django.db import migrations, models
import links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_link', models.URLField(max_length=2048)),
                ('link_id', models.CharField(default=links.models.gen_random_key, max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
